-- MySQL
create table person (
                        id integer AUTO_INCREMENT PRIMARY KEY,
                        full_name varchar(124) UNIQUE,
                        birthday_year integer NOT NULL
);

create table book (
                      id integer AUTO_INCREMENT PRIMARY KEY,
                      person_id integer REFERENCES person(id) ON DELETE SET NULL,
                      title varchar(100) NOT NULL ,
                      author varchar(100) NOT NULL ,
                      year integer NOT NULL
);

-- PostgreeSQL
CREATE TABLE person (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        full_name varchar(100) NOT NULL UNIQUE,
                        birthday_year int NOT NULL
);

CREATE TABLE book (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      person_id int REFERENCES person(id) ON DELETE SET NULL,
                      title varchar(100) NOT NULL,
                      author varchar(100) NOT NULL,
                      year int NOT NULL
);